apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - docker-secret.yaml

namespace: default

commonLabels:
  environment: local
  app: vault-legacy-app
  tier: backend

commonAnnotations:
  app.kubernetes.io/part-of: vault-legacy
  app.kubernetes.io/environment: local