apiVersion: v1
kind: Service
metadata:
  name: vault-legacy-app-service
  labels:
    app: vault-legacy-app
    env: prod
    cluster: eks
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vault-legacy-app
    tier: backend
    env: prod
    cluster: eks